# version: "3.9"

services:
  api:
    build: ./nomadWheels_Api
    command: python manage.py runserver 0.0.0.0:8000
    container_name: nomadwheels_api
    ports:
      - "8080:8000"   # adjust if your app runs on 8000
    env_file:
      - ./nomadWheels_Api/.env
    volumes:
      - ./nomadWheels_Api:/app
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: nomadwheels

volumes:
  postgres_data: